<a href="https://colab.research.google.com/github/UmaGhildiyal/Deep_Neural_Networks_YT/blob/main/gradient_descent.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
 import numpy as np
 import pandas as pd
 import tensorflow as tf
 from tensorflow import keras
 import matplotlib.pyplot as plt
 %matplotlib inline

In [4]:
df = pd.DataFrame({
    'age' : [22,25,47,52,46,56,55,60,62,61,18,28,27,29,49,55,25,58,19,18,21,26,40,45,50,54,23],
    'affordibility' : [1,0,1,0,1,1,0,0,1,1,1,1,0,0,1,1,0,1,0,1,1,0,1,1,1,1,1],
    'bought_insurance' : [0,0,1,0,1,1,0,1,1,1,0,0,0,0,1,1,1,1,0,0,0,0,1,1,1,1,0]
})
df.head()

age  affordibility  bought_insurance
0   22              1                 0
1   25              0                 0
2   47              1                 1
3   52              0                 0
4   46              1                 1

In [5]:
# train test split

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(df[['age','affordibility']], df.bought_insurance , test_size = 0.2, random_state = 25)

In [ ]:
print(len(X_train), len(X_test))

21 6


In [6]:
# scaling ---> more precise predictions
# ml model tends to work better
# age, affordibility ---> same scale ---> in range [0,1]
# age = age/100

X_train_scaled = X_train.copy()
X_train_scaled['age'] = X_train_scaled['age'] / 100

X_test_scaled = X_test.copy()
X_test_scaled['age'] = X_test_scaled['age'] / 100


In [ ]:
X_train_scaled

age  affordibility
0   0.22              1
13  0.29              0
6   0.55              0
17  0.58              1
24  0.50              1
19  0.18              1
25  0.54              1
16  0.25              0
20  0.21              1
3   0.52              0
7   0.60              0
1   0.25              0
5   0.56              1
26  0.23              1
8   0.62              1
18  0.19              0
12  0.27              0
23  0.45              1
22  0.40              1
15  0.55              1
4   0.46              1

In [18]:
# model training
# 1 output, 2 inputs, activation = sigmoid, weight = 1 , bias = 0

model = keras.Sequential([
    keras.layers.Dense(
        1,
        input_shape = [2,],
        activation = 'sigmoid',
        kernel_initializer = 'ones',
        bias_initializer = 'zero')
])

# model compile
# binary_crossentropy is same as log loss

model.compile(
    optimizer = 'adam',
    loss = 'binary_crossentropy',
    metrics = ['accuracy']
)

# model fit
model.fit(X_train_scaled, y_train, epochs = 5000)

Streaming output truncated to the last 5000 lines.
1/1 [==============================] - 0s 10ms/step - loss: 0.4871 - accuracy: 0.7619
Epoch 2502/5000
1/1 [==============================] - 0s 11ms/step - loss: 0.4870 - accuracy: 0.7619
Epoch 2503/5000
1/1 [==============================] - 0s 10ms/step - loss: 0.4870 - accuracy: 0.7619
Epoch 2504/5000
1/1 [==============================] - 0s 12ms/step - loss: 0.4870 - accuracy: 0.7619
Epoch 2505/5000
1/1 [==============================] - 0s 11ms/step - loss: 0.4869 - accuracy: 0.7619
Epoch 2506/5000
1/1 [==============================] - 0s 11ms/step - loss: 0.4869 - accuracy: 0.7619
Epoch 2507/5000
1/1 [==============================] - 0s 12ms/step - loss: 0.4868 - accuracy: 0.7619
Epoch 2508/5000
1/1 [==============================] - 0s 11ms/step - loss: 0.4868 - accuracy: 0.7619
Epoch 2509/5000
1/1 [==============================] - 0s 14ms/step - loss: 0.4867 - accuracy: 0.7619
Epoch 2510/5000
1/1 [==========================

In [ ]:
model.evaluate(X_test_scaled, y_test)

1/1 [==============================] - 0s 194ms/step - loss: 0.3456 - accuracy: 0.8333


[0.3455778658390045, 0.8333333134651184]

In [ ]:
X_test_scaled

age  affordibility
2   0.47              1
10  0.18              1
21  0.26              0
11  0.28              1
14  0.49              1
9   0.61              1

In [ ]:
model.predict(X_test_scaled)

1/1 [==============================] - 0s 140ms/step


array([[0.76754946],
       [0.3960877 ],
       [0.15774846],
       [0.5338377 ],
       [0.78684235],
       [0.8781276 ]], dtype=float32)

In [ ]:
y_test

2     1
10    0
21    0
11    0
14    1
9     1
Name: bought_insurance, dtype: int64

In [ ]:
# final weight, w1, w2, b
coef, intercept = model.get_weights()
coef, intercept

(array([[5.573512 ],
        [1.6991647]], dtype=float32),
 array([-3.12419], dtype=float32))

# Building Neural Network from scratch


*  from python w/o tensorflow



In [ ]:
def sigmoid(x):
  import math
  return 1 / (1 + math.exp(-x))

sigmoid(18)

0.9999999847700205

In [ ]:
# prediction function: sum(wi*xi + b)

def prediction_function(age, affordibility):
  weighted_sum = coef[0]*age +coef[1]*affordibility + intercept
  return sigmoid(weighted_sum)


In [ ]:
prediction_function(.47, 1)
# model predicted : array([[0.76754946],
# works once we have the weights and bias

<ipython-input-14-f2047d5e8e23>:3: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  return 1 / (1 + math.exp(-x))


0.7675494655492734

In [ ]:
prediction_function(.18, 1)
# model : [0.3960877]

<ipython-input-14-f2047d5e8e23>:3: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  return 1 / (1 + math.exp(-x))


0.39608772748632987

# Gradient Descent from scracth

In [8]:
def log_loss(y_true, y_predicted):
    epsilon = 1e-15
    y_predicted_new = [max(i,epsilon) for i in y_predicted]
    y_predicted_new = [min(i,1-epsilon) for i in y_predicted_new]
    y_predicted_new = np.array(y_predicted_new)
    return -np.mean(y_true*np.log(y_predicted_new)+(1-y_true)*np.log(1-y_predicted_new))


In [9]:
def sigmoid_numpy(X):
   return 1/(1+np.exp(-X))

sigmoid_numpy(np.array([12,0,1]))

array([0.99999386, 0.5       , 0.73105858])

In [ ]:
# gradient descent function helps to find weights and bias
# vector function

def gradient_descent(age, affordability, y_true, epochs, loss_thresold):
    w1 = w2 = 1
    bias = 0
    rate = 0.5
    n = len(age)
    for i in range(epochs):
        weighted_sum = w1 * age + w2 * affordability + bias
        y_predicted = sigmoid_numpy(weighted_sum)
        loss = log_loss(y_true, y_predicted)

        #weight update
        w1d = (1/n)*np.dot(np.transpose(age),(y_predicted-y_true))
        w2d = (1/n)*np.dot(np.transpose(affordability),(y_predicted-y_true))

        bias_d = np.mean(y_predicted-y_true)
        w1 = w1 - rate * w1d
        w2 = w2 - rate * w2d
        bias = bias - rate * bias_d

        print (f'Epoch:{i}, w1:{w1}, w2:{w2}, bias:{bias}, loss:{loss}')

        if loss<=loss_thresold:
            break

    return w1, w2, bias

In [ ]:
# Call the function
gradient_descent(X_train_scaled['age'], X_train_scaled['affordibility'], y_train, 1000, 0.4386)

Epoch:0, w1:0.9826009738830817, w2:0.965210718860606, bias:-0.09949736021942848, loss:0.6657455469538763
Epoch:1, w1:0.9699341038305147, w2:0.9375683867850162, bias:-0.18695778277694258, loss:0.6444332859491988
Epoch:2, w1:0.9615467777717888, w2:0.9164695329528318, bias:-0.26356431959629983, loss:0.6284607071235907
Epoch:3, w1:0.9569450200140835, w2:0.9011982933514219, bias:-0.3305859650587859, loss:0.6165763019660284
Epoch:4, w1:0.9556318898929159, w2:0.8909985221706849, bias:-0.3892847200379514, loss:0.6077312653233522
Epoch:5, w1:0.9571347787012647, w2:0.8851283247268951, bias:-0.44085104448182577, loss:0.6010936815748452
Epoch:6, w1:0.9610219279341647, w2:0.8828956430024146, bias:-0.48636600979344957, loss:0.5960311299819564
Epoch:7, w1:0.966910280026799, w2:0.8836776869188894, bias:-0.5267844653500466, loss:0.5920782652674909
Epoch:8, w1:0.9744672260463585, w2:0.8869284589456251, bias:-0.5629327245410065, loss:0.588901060995584
Epoch:9, w1:0.9834085286204046, w2:0.8921784495559433

(4.462592333795445, 1.681475857792042, -2.685410966265162)

In [ ]:
coef, intercept
#almost replicated?

(array([[5.573512 ],
        [1.6991647]], dtype=float32),
 array([-3.12419], dtype=float32))

# Implement Neural network in Python


*   write our own custom class
*   create fit method
*   create prediction function





In [14]:
class myNN:
  def __init__(self):
    self.w1 = 1
    self.w2 = 1
    self.bias = 0

  def fit(self, X, y, epochs, loss_thresold):
    self.w1, self.w2, self.bias = self.gradient_descent(X['age'], X['affordibility'], y, epochs, loss_thresold)

  def predict(self, X_test):
    weighted_sum = self.w1 * X_test['age'] + self.w2 * X_test['affordibility'] + self.bias
    return sigmoid_numpy(weighted_sum)

  def gradient_descent(self, age, affordability, y_true, epochs, loss_thresold):
    w1 = w2 = 1
    bias = 0
    rate = 0.5
    n = len(age)
    for i in range(epochs):
        weighted_sum = w1 * age + w2 * affordability + bias
        y_predicted = sigmoid_numpy(weighted_sum)
        loss = log_loss(y_true, y_predicted)

        #weight update
        w1d = (1/n)*np.dot(np.transpose(age),(y_predicted-y_true))
        w2d = (1/n)*np.dot(np.transpose(affordability),(y_predicted-y_true))

        bias_d = np.mean(y_predicted-y_true)
        w1 = w1 - rate * w1d
        w2 = w2 - rate * w2d
        bias = bias - rate * bias_d

        if i%50==0:
          print (f'Epoch:{i}, w1:{w1}, w2:{w2}, bias:{bias}, loss:{loss}')

        if loss<=loss_thresold:
          print (f'Epoch:{i}, w1:{w1}, w2:{w2}, bias:{bias}, loss:{loss}')
          break

    return w1, w2, bias

In [15]:
customModel = myNN()
customModel.fit(X_train_scaled, y_train, epochs=500, loss_thresold=0.4631)

Epoch:0, w1:0.9826009738830817, w2:0.965210718860606, bias:-0.09949736021942848, loss:0.6657455469538763
Epoch:50, w1:1.584361723197093, w2:1.2808555802400319, bias:-1.2316615680958156, loss:0.5384773066487856
Epoch:100, w1:2.333908701143997, w2:1.5024574939778497, bias:-1.6972249977290008, loss:0.5049431881802899
Epoch:150, w1:3.0331326378318746, w2:1.5949889778707547, bias:-2.0477929267959647, loss:0.4799885809135941
Epoch:192, w1:3.574850825067105, w2:1.6353941439801192, bias:-2.295648389178997, loss:0.4629445989153857


In [16]:
customModel.predict(X_test_scaled)

2     0.734958
10    0.495805
21    0.203237
11    0.584362
14    0.748650
9     0.820598
dtype: float64

In [19]:
model.predict(X_test_scaled)

1/1 [==============================] - 0s 135ms/step


array([[0.76754946],
       [0.39608768],
       [0.15774845],
       [0.5338377 ],
       [0.7868423 ],
       [0.8781275 ]], dtype=float32)